#pragma once

#define PLOOPY_DRAGSCROLL_FIXED 1
#define PLOOPY_DRAGSCROLL_INVERT 1
#define PLOOPY_DRAGSCROLL_DPI 100  // Fixed-DPI Drag Scroll
#define PLOOPY_DRAGSCROLL_MOMENTARY 1
#define PLOOPY_DRAGSCROLL_DIVISOR_V 75.0
#define PLOOPY_DRAGSCROLL_DIVISOR_H 75.0
